### ISSUE TITLE
Add flavor of Markdown (or related guidance thereof)

### ISSUE THREAD

**Issue by osg-grafana** [grafana/writers-toolkit#156]
It is not clear if we are using a particular flavor or Markdown or not. This issue provides guidance about that.

**Comment by MattDodsonEnglish** [comment]
Hugo uses the goldmark engine to parse markdown. That engine doesn't have docs, but the [`extensions` dir](https://github.com/yuin/goldmark/tree/master/extension) of its code base has the added features. GFM probably works out the box.

Maybe all extensions work? The best way is to try on local site :shrug:. If a feature doesn't work, it probably just needs to be [enabled in the Hugo config](https://gohugo.io/getting-started/configuration-markup/).

**Comment by osg-grafana** [comment]
@JStickler, wanna grab this one?

**Comment by osg-grafana** [comment]
@jackw, want to provide pros/cons on this?

**Comment by JStickler** [comment]
@osg-grafana Happy to write it up, but I didn't think we'd had a chance to discuss a standard yet?

**Comment by jdbaldry** [comment]
As @MattDodsonEnglish mentioned, Hugo uses the Goldmark engine to parse Markdown. It is CommonMark compatible out of the box and is also extensible. The extensions we have enabled are defined in the website repository -- https://github.com/grafana/website/blob/master/config/_default/config.yaml#L103-L121.

I don't have a strong preference for any particular Markdown flavor.

**Comment by MattDodsonEnglish** [comment]
I'd  recommend doing nothing about this, and extending the configuration that Jack linked only when some need arises.

For example, if we discover that Github markdown has built in support for sidenotes, and a writer needs side notes and can't make them work in the default hugo parser, then they can post to the docs team channel and to initiate an investigation about whether it makes sense to add the hypothetical GFM feature to our config.

And I mean only to _extend_ the config. I think it'd be a bad idea to _change_ the config now, because who knows what edge cases it might break? And who would want to be responsible for auditing a change that could modify how Hugo renders markdown to HTML across every single page of the docs?

**Comment by JStickler** [comment]
_And who would want to be responsible for auditing a change that could modify how Hugo renders markdown to HTML across every single page of the docs?_

Worrying that adding a plugin would change how Hugo renders markdown assumes that we're already following a markdown standard.  Markdown itself is **_not_** standardized, and if we have not specified what standard we want contributors to follow, we are already running the risk of having HTML problems due to inconsistent formatting.  Or do we have some sort of linter that's been implemented to check markdown formatting?

**Comment by jdbaldry** [comment]
> Worrying that adding a plugin would change how Hugo renders markdown assumes that we're already following a markdown standard. 
We are at least CommonMark compliant given the use of goldmark Markdown parser. I believe we are also using some GFM features if I understand the Hugo configuration correctly and GFM is a strict superset of CommonMark (https://github.github.com/gfm/#what-is-github-flavored-markdown-).

If we want to document it, I would start with some reiteration of the above.

> Or do we have some sort of linter that's been implemented to check markdown formatting?

For each repository there should exist a workflow that performs a build using Hugo which must first parse the Markdown to successfully complete.
