### ISSUE TITLE
Add Vale vocab folder

### ISSUE THREAD

**Issue by heitortsergent** [grafana/writers-toolkit#327]
Add Vale vocab folder so we can include words to accept/reject from linting: https://vale.sh/docs/topics/vocab/.

**Comment by jdbaldry** [comment]
> In general, this means that ignore files are for style creators while vocabularies are for style users:

https://vale.sh/docs/topics/vocab/#relation-to-ignore-files

I wonder if we need this?

**Comment by heitortsergent** [comment]
Ah, after reading that, maybe we can close this. I just remember using vocabularies at my previous job, and I liked how easy it was to update them (I don't really understand how the dictionary files work 😞).

**Comment by jdbaldry** [comment]
Vocab is definitely easier since it applies across all rules.

I'm still learning about dictionary files and the resources are pretty scarce so I appreciate that it's not ideal.

I'm thinking of adding our own kind of vocabulary configuration that I can use to generate some of the rules and dictionaries from. I want something a bit more structured so that I can define a word once and it is automatically propagated to all the right places, like sentence case heading exceptions and the dictionary for product names.

**Comment by heitortsergent** [comment]
If we could use a combination of both, that would be awesome!

Also, maybe this could be a topic for our working group, about how to add words to the dictionary.

**Comment by jdbaldry** [comment]
I'd love to talk more about Hunspell dictionaries. I'm a novice myself but I can still explain what little I already know :)

**Comment by jdbaldry** [comment]
Closing this but I think we should keep in mind that individual repositories may want to use vocabularies and that at some point our dictionary needs to be documented.
