### ISSUE TITLE
Grafana.Timeless : "existing" false positive

### ISSUE THREAD

**Issue by BeverlyJaneJ** [grafana/writers-toolkit#449]
"existing" was flagged in my doc even though it was referring to an existing cluster and has nothing to do with software doc versions.

**Comment by jdbaldry** [comment]
Good flag, I see that it was raised in https://github.com/grafana/website/pull/17789/files#r1473409217.

In that case, it does seem that the use of "existing" is superfluous so we can work around the issue pretty easily with:

> For example, your configuration might already include `kube-state-metrics` in your Cluster, so you don't want the Helm chart to install another one.

instead of:

> For example, your configuration might already have an existing `kube-state-metrics` in your Cluster, so you don't want the Helm chart to install another one.

I don't see a good way of adding exceptions for "existing X" where X is unrelated to the software and I do think we should be reminded about the importance of timeless documentation so I think the workaround is easier.

I've updated the title of this issue and added some labels to reflect the false positive in this case and if it repeats, I'll definitely reevaluate its value.
